#if os(iOS)
import SwiftUI

/// The credits of the external photos prepared by the photo pipeline (`Resources/PhotoCredits.json`,
/// generated by scripts/photos): « Photos fournies par Pexels », then one line per photo — who took
/// it, where it comes from, under which licence. Out of the game, in Paramètres › À propos.
struct PhotoCredits: Decodable {
    struct Item: Decodable, Identifiable {
        let provider: String
        let photographer: String
        let photographerUrl: String
        let sourceUrl: String
        let license: String
        let licenseUrl: String
        let title: String
        let attribution: String
        let cases: [String]

        var id: String { sourceUrl + attribution }
    }

    let pexels: Bool
    let items: [Item]

    /// The bundled credits (nil when no external photo is shipped).
    static let bundled: PhotoCredits? = {
        guard let url = Bundle.module.url(forResource: "PhotoCredits", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let credits = try? JSONDecoder().decode(PhotoCredits.self, from: data),
              !credits.items.isEmpty else { return nil }
        return credits
    }()
}

/// Paramètres › À propos › Crédits photos (V4): a paper sheet — « ‹ À propos », the title over a
/// 1.5 pt ink rule, the promise (real photographs only), then one row per photo separated by thin
/// ink rules: the attribution, its source and licence as underlined links.
struct PhotoCreditsView: View {
    let credits: PhotoCredits
    let onClose: () -> Void

    private static let pexelsHome = URL(string: "https://www.pexels.com")

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: Trace.Spacing.l) {
                BackLink(title: L10n.t("settings.about"), identifier: "credits.back", onPaper: true, action: onClose)
                PaperworkHeader(title: L10n.t("credits.button"))
                Text(L10n.t("credits.intro"))
                    .font(Trace.Fonts.body)
                    .foregroundStyle(Trace.Colors.ink2)
                    .fixedSize(horizontal: false, vertical: true)
                if credits.pexels, let home = Self.pexelsHome {
                    Link(destination: home) {
                        Text(L10n.t("credits.pexels")).underline()
                    }
                    .font(Trace.Fonts.link)
                    .foregroundStyle(Trace.Colors.ink)
                    .frame(minHeight: Trace.Height.hit)
                    .accessibilityIdentifier("credits.pexels")
                }
                VStack(spacing: 0) {
                    PaperworkRule()
                    ForEach(credits.items) { item in
                        VStack(alignment: .leading, spacing: 2) {
                            Text(item.attribution)
                                .font(Trace.Fonts.callout)
                                .foregroundStyle(Trace.Colors.ink)
                                .fixedSize(horizontal: false, vertical: true)
                                .padding(.top, Trace.Spacing.m)
                            HStack(spacing: Trace.Spacing.l) {
                                if let url = URL(string: item.sourceUrl), !item.sourceUrl.isEmpty {
                                    Link(destination: url) { Text(L10n.t("credits.source")).underline() }
                                        .frame(minHeight: Trace.Height.hit)
                                }
                                if let url = URL(string: item.licenseUrl), !item.licenseUrl.isEmpty {
                                    Link(destination: url) { Text(item.license).underline() }
                                        .frame(minHeight: Trace.Height.hit)
                                }
                            }
                            .font(Trace.Fonts.caption)
                            .foregroundStyle(Trace.Colors.ink2)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .overlay(alignment: .bottom) { PaperworkRule() }
                        .accessibilityElement(children: .contain)
                    }
                }
                .tint(Trace.Colors.ink)
                Button(L10n.t("a11y.close"), action: onClose)
                    .buttonStyle(CTAButtonStyle(kind: .outline, onPaper: true))
                    .accessibilityIdentifier("credits.close")
                    .padding(.top, Trace.Spacing.s)
            }
            .padding(.horizontal, Paperwork.sheetPadding)
            .padding(.vertical, Paperwork.sheetPadding)
        }
        .scrollBounceBehavior(.basedOnSize)
        .background(Trace.Colors.paper.overlay(PaperGrain()).ignoresSafeArea())
        .accessibilityIdentifier("credits.view")
    }
}
#endif
