#if os(iOS)
import SwiftUI

/// The credits of the external photos prepared by the photo pipeline (`Resources/PhotoCredits.json`,
/// generated by scripts/photos): « Photos fournies par Pexels », then one line per photo — who took
/// it, where it comes from, under which licence. Out of the game, in Paramètres › À propos.
struct PhotoCredits: Decodable {
    struct Item: Decodable, Identifiable {
        let provider: String
        let photographer: String
        let photographerUrl: String
        let sourceUrl: String
        let license: String
        let licenseUrl: String
        let title: String
        let attribution: String
        let cases: [String]

        var id: String { sourceUrl + attribution }
    }

    let pexels: Bool
    let items: [Item]

    /// The bundled credits (nil when no external photo is shipped).
    static let bundled: PhotoCredits? = {
        guard let url = Bundle.module.url(forResource: "PhotoCredits", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let credits = try? JSONDecoder().decode(PhotoCredits.self, from: data),
              !credits.items.isEmpty else { return nil }
        return credits
    }()
}

struct PhotoCreditsView: View {
    let credits: PhotoCredits
    let onClose: () -> Void

    private static let pexelsHome = URL(string: "https://www.pexels.com")

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                BackLink(title: L10n.t("settings.about"), identifier: "credits.back", action: onClose)
                Text(L10n.t("credits.button"))
                    .font(Trace.Fonts.title)
                    .foregroundStyle(Trace.Colors.text)
                    .fixedSize(horizontal: false, vertical: true)
                    .accessibilityAddTraits(.isHeader)
                Text(L10n.t("credits.intro"))
                    .font(Trace.Fonts.body)
                    .foregroundStyle(Trace.Colors.text2)
                    .fixedSize(horizontal: false, vertical: true)
                if credits.pexels, let home = Self.pexelsHome {
                    Link(L10n.t("credits.pexels"), destination: home)
                        .font(Trace.Fonts.link)
                        .foregroundStyle(Trace.Colors.benText)
                        .frame(minHeight: Trace.Height.hit)
                        .accessibilityIdentifier("credits.pexels")
                }
                VStack(spacing: 0) {
                    ForEach(Array(credits.items.enumerated()), id: \.element.id) { index, item in
                        VStack(alignment: .leading, spacing: 6) {
                            Text(item.attribution)
                                .font(Trace.Fonts.callout)
                                .foregroundStyle(Trace.Colors.text)
                                .fixedSize(horizontal: false, vertical: true)
                            HStack(spacing: 16) {
                                if let url = URL(string: item.sourceUrl), !item.sourceUrl.isEmpty {
                                    Link(L10n.t("credits.source"), destination: url)
                                }
                                if let url = URL(string: item.licenseUrl), !item.licenseUrl.isEmpty {
                                    Link(item.license, destination: url)
                                }
                            }
                            .font(Trace.Fonts.caption)
                            .foregroundStyle(Trace.Colors.benText)
                        }
                        .padding(.horizontal, 16)
                        .padding(.vertical, 12)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .overlay(alignment: .bottom) {
                            if index < credits.items.count - 1 {
                                Rectangle().fill(Trace.Colors.line).frame(height: 1).padding(.leading, 16)
                            }
                        }
                        .accessibilityElement(children: .combine)
                    }
                }
                .benCard()
                Button(L10n.t("a11y.close"), action: onClose)
                    .buttonStyle(CTAButtonStyle(kind: .outline))
                    .accessibilityIdentifier("credits.close")
            }
            .padding(.horizontal, 16)
            .padding(.vertical, 20)
        }
        .background(DeskBackdrop())
        .accessibilityIdentifier("credits.view")
    }
}
#endif
